from typing import Any

from modelcluster.queryset import FakeQuerySet as FakeQuerySet
from taggit.managers import TaggableManager, _TaggableManager

class _ClusterTaggableManager(_TaggableManager):
    def get_tagged_item_manager(self) -> Any: ...
    def get_queryset(self, extra_filters: Any | None = None) -> Any: ...
    def add(self, *tags: Any) -> None: ...
    def remove(self, *tags: Any) -> None: ...
    def set(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self) -> None: ...

class ClusterTaggableManager(TaggableManager):
    _need_commit_after_assignment: bool
    def __get__(self, instance: Any, model: type) -> _ClusterTaggableManager: ...
    def value_from_object(self, instance: Any) -> list[Any]: ...
