from collections.abc import Callable, Iterator, Sequence
from typing import Any, Self

from django.db.models import Model, Q

FILTER_EXPRESSION_TOKENS: dict[str, Callable[..., Callable[[Any], bool]]]

def test_exact(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_iexact(
    model: type[Model], attribute_name: str, match_value: Any
) -> Callable[[Any], bool]: ...
def test_contains(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_icontains(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_lt(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_lte(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_gt(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_gte(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_in(
    model: type[Model], attribute_name: str, value_list: Sequence[Any]
) -> Callable[[Any], bool]: ...
def test_startswith(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_istartswith(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_endswith(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_iendswith(
    model: type[Model], attribute_name: str, value: Any
) -> Callable[[Any], bool]: ...
def test_range(
    model: type[Model], attribute_name: str, range_val: tuple[Any, Any]
) -> Callable[[Any], bool]: ...
def test_isnull(
    model: type[Model], attribute_name: str, sense: bool
) -> Callable[[Any], bool]: ...
def test_regex(
    model: type[Model], attribute_name: str, regex_string: str
) -> Callable[[Any], bool]: ...
def test_iregex(
    model: type[Model], attribute_name: str, regex_string: str
) -> Callable[[Any], bool]: ...

class FakeQuerySetIterable:
    queryset: FakeQuerySet
    def __init__(self, queryset: FakeQuerySet) -> None: ...

class ModelIterable(FakeQuerySetIterable):
    def __iter__(self) -> Iterator[Model]: ...

class DictIterable(FakeQuerySetIterable):
    def __iter__(self) -> Iterator[dict[str, Any]]: ...

class ValuesListIterable(FakeQuerySetIterable):
    def __iter__(self) -> Iterator[tuple[Any, ...]]: ...

class FlatValuesListIterable(FakeQuerySetIterable):
    def __iter__(self) -> Iterator[Any]: ...

class FakeQuerySet:
    model: type[Model]
    results: list[Model]
    dict_fields: Sequence[str]
    tuple_fields: Sequence[str]
    iterable_class: type[FakeQuerySetIterable]
    ordered: bool
    def __init__(self, model: type[Model], results: list[Model]) -> None: ...
    def all(self) -> Self: ...
    def get_clone(self, results: list[Any] | None = None) -> FakeQuerySet: ...
    def resolve_q_object(self, q_object: Q) -> Callable[[Any], bool]: ...
    def filter(self, *args: Q, **kwargs: Any) -> FakeQuerySet: ...
    def exclude(self, *args: Q, **kwargs: Any) -> FakeQuerySet: ...
    def get(self, *args: Q, **kwargs: Any) -> Model: ...
    def count(self) -> int: ...
    def exists(self) -> bool: ...
    def first(self) -> Model | None: ...
    def last(self) -> Model | None: ...
    def select_related(self, *args: str) -> Self: ...
    def prefetch_related(self, *args: Any) -> Self: ...
    def only(self, *args: str) -> Self: ...
    def defer(self, *args: str) -> Self: ...
    def values(self, *fields: str) -> FakeQuerySet: ...
    def values_list(self, *fields: str, flat: bool | None = None) -> FakeQuerySet: ...
    def order_by(self, *fields: str) -> FakeQuerySet: ...
    def distinct(self, *fields: str) -> FakeQuerySet: ...
    @property
    def _result_cache(self) -> list[Any]: ...
    @_result_cache.setter
    def _result_cache(self, val: Any) -> None: ...
    def __getitem__(self, k: int | slice) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __nonzero__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
